/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export type CheapApiNode = CheapApi
export declare class CheapApi {
  static withMongodb(connectionUri: string, database: string, collection: string, ttlSeconds: number | undefined | null, cacheErrors: boolean, maxCacheableBodyBytes: number): Promise<CheapApiNode>
  intercept(url: string, method: string, headers: Record<string, string>, body?: string | undefined | null): Promise<any>
}
