/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface JsMongoAdapterConfig {
  connectionUri: string
  database: string
  collection: string
  ttlSeconds?: number
}
export interface JsInterceptorConfig {
  cacheErrors: boolean
  maxCacheableBodyBytes: number
}
export interface JsInterceptRequest {
  url: string
  method: string
  headers: Record<string, string>
  body?: string
}
export interface JsInterceptResponse {
  status: number
  headers: Record<string, string>
  body: string
  fromCache: boolean
  cacheKey: string
}
export declare class CheapApi {
  /** Initialize the Cheap API with a MongoDB backend. */
  static withMongodb(mongoCfg: JsMongoAdapterConfig, interceptorCfg: JsInterceptorConfig): Promise<CheapApi>
  /** Intercept a request and return a response (from cache or upstream). */
  intercept(req: JsInterceptRequest): Promise<JsInterceptResponse>
}
